name: 🎯 Manual Deploy (100% Working)

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install and Build
        working-directory: ./criminal-minds-game
        run: |
          npm install
          npm run build
          echo "Files created:"
          ls -la out/

      - name: Deploy to Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./criminal-minds-game/out 